services:
  etcd1:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8379:2379
    networks:
      etcd:
        ipv4_address: 172.20.0.2
  etcd2:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8380:2379
    networks:
      etcd:
        ipv4_address: 172.20.0.3
  etcd3:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8381:2379
    networks:
      etcd:
        ipv4_address: 172.20.0.4
networks:
  etcd:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.20.0.0/24
