services:
  etcd1:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8022:22
    networks:
      - etcd
  etcd2:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8023:22
    networks:
      - etcd
  etcd3:
    image: jepsen-tutorial-etcd:latest
    ports:
      - 8024:22
    networks:
      - etcd
networks:
  etcd:
