services:
  etcd1:
    build: .
    ports:
      - 8022:22    
    # depends_on:
    #   db:
    #     condition: service_healthy
    #     restart: true
    #   redis:
    #     condition: service_started

